#
# Run pitest and update github in a single step. Until and unless I get outside contributions, this suffices
#
name: Run Pitest
on:
  push:
    branches: ["renovate/*"]
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write
  issues: write

jobs:
  pull-request-ci:
    # Only run on PRs from the repo. PRs from forks will fail due to lack of permissions and
    # must use the two stage process
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      with:
        fetch-depth: 0 # so we can work out our version correctly

    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4

    # A push will be from Renovate, so I can agree to the terms.
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4
      if: github.actor != 'andrewaylett' && github.event_name != 'push'
      with:
        dependency-graph: 'generate-and-submit'

    - name: Setup Gradle Build Scan
      uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4
      if: github.actor == 'andrewaylett' || github.event_name == 'push'
      with:
        dependency-graph: 'generate-and-submit'
        build-scan-publish: 'true'
        build-scan-terms-of-use-agree: 'yes'
        build-scan-terms-of-use-url: https://gradle.com/help/legal-terms-of-use

    - name: Execute Pitest
      run: ./gradlew --no-configuration-cache pitest-github
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
