name: Publish Plugin

on:
  release:
    types: [created]

permissions:
  contents: write
  checks: write
  packages: write

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0 # so we can work out our version correctly

    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4
      with:
        dependency-graph: 'generate-and-submit'
        build-scan-publish: 'true'
        build-scan-terms-of-use-agree: 'yes'
        build-scan-terms-of-use-url: https://gradle.com/help/legal-terms-of-use

    - name: Publish to GitHub Packages
      run: ./gradlew publishMavenJavaPublicationToGitHubPackagesRepository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to OSSRH
      run: ./gradlew --no-configuration-cache -Dorg.gradle.unsafe.isolated-projects=false publishMavenJavaPublicationToSonatypeRepository closeSonatypeStagingRepository
      env:
        OSSRH_TOKEN_USER: ${{ secrets.OSSRH_TOKEN_USER }}
        OSSRH_TOKEN_PASSWORD: ${{ secrets.OSSRH_TOKEN_PASSWORD }}
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
